// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuqkmunveyjjnpvfldqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cWttdW52ZXlqam5wdmZsZHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzA3MDIsImV4cCI6MjA2MTI0NjcwMn0.b74mwAPV8m2mep8d1-qtPW_RFbBaIE-FQwg9yPqvuvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);